#[derive(Clone, Debug)]
pub struct UserInfo {
    pub user_id: i32,
    pub name: String,
}

#[allow(non_snake_case)]
#[derive(Clone, Debug)]
pub struct AdbPackageInfoUser {
    pub userId: i32,
    pub ceDataInode: i64,
    pub deDataInode: i64,
    pub installed: bool,
    pub hidden: bool,
    pub suspended: bool,
    pub distractionFlags: i32,
    pub stopped: bool,
    pub notLaunched: bool,
    pub enabled: i32,
    pub instant: bool,
    pub virtualField: bool,
    pub quarantined: bool,
    pub installReason: i32,
    pub dataDir: String,
    pub firstInstallTime: String,
    pub uninstallReason: i32,
    // pub overlayPaths: Vec<String>,
    // pub legacyOverlayPaths: Vec<String>,
    pub lastDisabledCaller: String,
    pub gids: Vec<i32>,
    pub runtimePermissions: Vec<String>,
}

#[allow(non_snake_case)]
#[derive(Clone)]
pub struct AdbPackageInfo {
    pub appUri: String,
    pub appChecksum: String,
    pub appId: i32,
    pub sharedUser: String,
    pub pkg: String,
    pub codePath: String,
    pub resourcePath: String,
    pub legacyNativeLibraryDir: String,
    pub extractNativeLibs: bool,
    pub primaryCpuAbi: String,
    pub secondaryCpuAbi: String,
    pub cpuAbiOverride: String,
    pub versionCode: i32,
    pub minSdk: i32,
    pub targetSdk: i32,
    pub minExtensionVersions: String,
    pub versionName: String,
    pub hiddenApiEnforcementPolicy: String,
    pub usesNonSdkApi: bool,
    pub splits: String,
    pub apkSigningVersion: i32,
    pub flags: String,
    pub privateFlags: String,
    pub forceQueryable: bool,
    pub pageSizeCompat: i32,
    pub queriesPackages: Vec<String>,
    pub queriesIntents: Vec<String>,
    pub scannedAsStoppedSystemApp: bool,
    pub supportsScreens: String,
    pub staticLibraries: Vec<String>,
    pub usesLibraries: Vec<String>,
    pub usesOptionalLibraries: Vec<String>,
    pub usesLibraryFiles: Vec<String>,
    pub timeStamp: String,
    pub lastUpdateTime: String,
    pub installerPackageName: String,
    pub installerPackageUid: i32,
    pub initiatingPackageName: String,
    pub originatingPackageName: String,
    pub packageSource: i32,
    pub appMetadataFilePath: String,
    pub appMetadataSource: i32,
    pub signatures: String,
    pub installPermissionsFixed: bool,
    pub pkgFlags: String,
    pub privatePkgFlags: String,
    pub apexModuleName: String,
    pub overlayTarget: String,
    pub overlayCategory: String,
    pub declaredPermissions: Vec<String>,
    pub installPermissions: String,
    pub users: Vec<AdbPackageInfoUser>,
}

impl Default for AdbPackageInfo {
    fn default() -> Self {
        Self {
            appUri: String::new(),
            appChecksum: String::new(),
            appId: 0,
            sharedUser: String::new(),
            pkg: String::new(),
            codePath: String::new(),
            resourcePath: String::new(),
            legacyNativeLibraryDir: String::new(),
            extractNativeLibs: false,
            primaryCpuAbi: String::new(),
            secondaryCpuAbi: String::new(),
            cpuAbiOverride: String::new(),
            versionCode: 0,
            minSdk: 0,
            targetSdk: 0,
            minExtensionVersions: String::new(),
            versionName: String::new(),
            hiddenApiEnforcementPolicy: String::new(),
            usesNonSdkApi: false,
            splits: String::new(),
            apkSigningVersion: 0,
            flags: String::new(),
            privateFlags: String::new(),
            forceQueryable: false,
            pageSizeCompat: 0,
            queriesPackages: Vec::new(),
            queriesIntents: Vec::new(),
            scannedAsStoppedSystemApp: false,
            supportsScreens: String::new(),
            staticLibraries: Vec::new(),
            usesLibraries: Vec::new(),
            usesOptionalLibraries: Vec::new(),
            usesLibraryFiles: Vec::new(),
            timeStamp: String::new(),
            lastUpdateTime: String::new(),
            installerPackageName: String::new(),
            installerPackageUid: 0,
            initiatingPackageName: String::new(),
            originatingPackageName: String::new(),
            packageSource: 0,
            appMetadataFilePath: String::new(),
            appMetadataSource: 0,
            signatures: String::new(),
            installPermissionsFixed: false,
            pkgFlags: String::new(),
            privatePkgFlags: String::new(),
            apexModuleName: String::new(),
            overlayTarget: String::new(),
            overlayCategory: String::new(),
            declaredPermissions: Vec::new(),
            installPermissions: String::new(),
            users: Vec::new(),
        }
    }
}

#[derive(Clone, Debug)]
pub struct ApkInfo {
    pub path: String,
    pub sha256: String,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone)]
pub struct PackageFingerprint {
    pub pkg: String,
    pub codePath: String,
    pub versionCode: i32,
    pub versionName: String,
    pub flags: String,
    pub privateFlags: String,
    pub installPermissions: Vec<String>,
    pub users: Vec<AdbPackageInfoUser>,
    pub lastUpdateTime: String,
    pub pkgChecksum: String,
    pub dumpText: String,
}
